Update codeowners
ProjectPythia/projectpythia.github.io pull request #105
Opened 2021-06-14 18:42 UTC by andersy005

Fixes #65. Do we want to close #79, too?

2021-06-14 18:56 UTC, clyne commented
Will we have round-robin scheduling enabled after this? Thanks.

2021-06-14 19:10 UTC, kmpaul requested changes
What do you think about this?

2021-06-14 19:10 UTC, kmpaul commented on .github/CODEOWNERS
> +*   @ProjectPythia/infrastructure @ProjectPythia/education
Should this be used instead?

```suggestion
*   @ProjectPythia/infrastructure

/content/ @ProjectPythia/infrastructure @ProjectPythia/education
```

2021-06-14 19:56 UTC, clyne approved these changes

2021-06-14 20:47 UTC, brian-rose approved these changes

2021-06-15 15:56 UTC, kmpaul approved these changes
Thanks, @andersy005!

2021-06-15 16:41 UTC, brian-rose commented
Well, this is annoying. The builds are [completing on readthedocs](https://readthedocs.org/projects/projectpythia/builds/14015731/), but forever reported as "Pending" here.

2021-06-15 16:51 UTC, clyne commented
That would explain what is going on with #97

2021-06-15 17:48 UTC, merged