Add Twitter button to Portal Navbar
ProjectPythia/projectpythia.github.io pull request #151
Opened 2021-09-14 22:30 UTC by jukent

Closes https://github.com/ProjectPythia/projectpythia.github.io/issues/136

2021-09-20 22:40 UTC, jukent commented
I tried a few ways to push the navbar Twitter button to the right but am having no luck. I would appreciate another set of eyes on the html, as well as style opinions. Also, maybe it's not that important to have the button on the right?

2021-09-20 22:56 UTC, kmpaul requested changes

2021-09-20 22:56 UTC, kmpaul commented on sphinx_pythia_theme/header.html
> +      <ul class="nav navbar-nav navbar-right">
```suggestion
      <ul class="navbar-nav ms-auto">
```

2021-09-20 22:59 UTC, kmpaul commented
@jukent:  This is Bootstrap 5, so you need to make sure you are reading the documentation for the correct version of Bootstrap.

I fixed the right-align issue, but I think the button seems out of place and doesn't match the theme.  Can we change the button to something that looks better with the theme?

2021-09-21 14:45 UTC, mgrover1 approved these changes
It looks great! Thanks @jukent for adding this

2021-11-04 21:33 UTC, jukent commented
@kmpaul Is there something significantly different between this portal sight and the Xdev blog? I would like to copy the way the Twitter button looks over there, but cannot seem to replicate it. Both are Bootstrap 5 correct?

2021-11-04 21:44 UTC, jukent commented
That makes sense then.

2021-11-18 19:58 UTC, jukent commented
Build failure with "Error: Unable to locate executable file: /usr/share/miniconda/condabin/mamba. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable." I don't think this is related to this small change.

2021-11-18 22:42 UTC, kmpaul approved these changes
This looks good!

2021-11-18 23:42 UTC, kmpaul commented
@mgrover1: This is read for review, again.

2021-11-19 14:18 UTC, mgrover1 approved these changes
Looks great - thanks @jukent ! 👍

2021-11-19 14:57 UTC, merged