Fix modal vs modal-button discrepancy in resource gallery
ProjectPythia/projectpythia.github.io pull request #236
Opened 2022-05-05 18:36 UTC by jukent

There are more modals than modal-buttons, so the modals that line up do not match the card from which they are opened.

2022-05-05 18:58 UTC, kmpaul requested changes

2022-05-05 18:58 UTC, kmpaul commented on portal/_extensions/truncatehtml.py
> +            if char == '&amp;':
This won't work. The `char` is always a single character so this check will always fail.  I would not change this back:

```suggestion
            if char == '&':
```

2022-05-05 19:00 UTC, kmpaul commented
This fix has already made some improvements.  In the preview link, I can see that there are 13 `class="modal"` objects and 12 `class="modal-btn"` objects.  So, it's getting better.

2022-05-05 20:17 UTC, kmpaul commented
> Interestingly enough, the above fix seems to have fixed the truncated Unidata card description. Not sure why. Maybe the original problematic rendering was a fluke and not reproducible.

I've been thinking about this fact a bit, and I'm bothered by it.  It seems that the problem with the description in the Unidata card that created the original modal mismatches (i.e., not having the `<a class="modal-btn">` tag in it) cannot be reproduced.  I still don't know why this happened, and I'm particularly afraid that it was a fluke and cannot be reproduced!

The reason I'm worried about this is because if an unreproducible error adding the modal button ever happens again (for whatever reason), then the gallery modals will get out of sync again.  I think there are 2 solutions to this problem:

1. Change the `custom.js` script functions to use a named *key*-based indexing (as you pointed out in (https://github.com/ProjectPythia/projectpythia.github.io/issues/235#issuecomment-1118858684).  But I'm not sure this is the best solution because it leaves `class="modal"` objects in the HTML without matching `class="modal-btn"` objects that bloats the HTML (even if the gallery modals still work properly).

2. Change the gallery generator extension to check to see if the `short_description` has the `ellipsis` string in it, such as changing:

   ```python
   if _len_html(item['description']) < max_descr_len:
       short_description = item['description']
       modal_str = ''
   else:
       short_description = th.truncate(
           item['description'], max_descr_len, ellipsis='<a class="modal-btn"> ...more</a>'
       )
       modal_str = f"""
   # ...contents removed for brevity...
   """
   ```

   to:

   ```python
   ellipsis_str = '<a class="modal-btn"> ...more</a>'
   short_description = th.truncate(item['description'], max_descr_len, ellipsis=ellipsis_str)
   if ellipsis_str in short_description:
       modal_str = f"""
   # ...contents cut for brevity...
   """
   else:
       modal_str = ''
   ```

   This solution *always* truncates the description string using the `truncate` function.  And it doesn't need the `_len_html` function at all.  However, if the description string is shorter than the `max_descr_len` (according to the `truncate` function), then it will add the `ellipsis_str` string to the end.  And *only if the `ellipsis_str` is added* does it create the `class="modal"` object.  

   This means that even if the `truncate` function fails for some mysterious reason, and it fails to truncate or something else weird happens, then it only creates the modal if the modal button actually exists.  I think this is safer.

2022-05-05 20:17 UTC, kmpaul commented
> Interestingly enough, the above fix seems to have fixed the truncated Unidata card description. Not sure why. Maybe the original problematic rendering was a fluke and not reproducible.

I've been thinking about this fact a bit, and I'm bothered by it.  It seems that the problem with the description in the Unidata card that created the original modal mismatches (i.e., not having the `<a class="modal-btn">` tag in it) cannot be reproduced.  I still don't know why this happened, and I'm particularly afraid that it was a fluke and cannot be reproduced!

The reason I'm worried about this is because if an unreproducible error adding the modal button ever happens again (for whatever reason), then the gallery modals will get out of sync again.  I think there are 2 solutions to this problem:

1. Change the `custom.js` script functions to use a named *key*-based indexing (as you pointed out in (https://github.com/ProjectPythia/projectpythia.github.io/issues/235#issuecomment-1118858684).  But I'm not sure this is the best solution because it leaves `class="modal"` objects in the HTML without matching `class="modal-btn"` objects that bloats the HTML (even if the gallery modals still work properly).

2. Change the gallery generator extension to check to see if the `short_description` has the `ellipsis` string in it, such as changing:

   ```python
   if _len_html(item['description']) < max_descr_len:
       short_description = item['description']
       modal_str = ''
   else:
       short_description = th.truncate(
           item['description'], max_descr_len, ellipsis='<a class="modal-btn"> ...more</a>'
       )
       modal_str = f"""
   # ...contents removed for brevity...
   """
   ```

   to:

   ```python
   ellipsis_str = '<a class="modal-btn"> ...more</a>'
   short_description = th.truncate(item['description'], max_descr_len, ellipsis=ellipsis_str)
   if ellipsis_str in short_description:
       modal_str = f"""
   # ...contents cut for brevity...
   """
   else:
       modal_str = ''
   ```

   This solution *always* truncates the description string using the `truncate` function.  And it doesn't need the `_len_html` function at all.  However, if the description string is shorter than the `max_descr_len` (according to the `truncate` function), then it will add the `ellipsis_str` string to the end.  And *only if the `ellipsis_str` is added* does it create the `class="modal"` object.  

   This means that even if the `truncate` function fails for some mysterious reason, and it fails to truncate or something else weird happens, then it only creates the modal if the modal button actually exists.  I think this is safer.

2022-05-05 21:44 UTC, jukent commented
Will address the shortening of the Unidata card in a separate PR.

2022-05-05 22:01 UTC, kmpaul approved these changes
Thanks for doing this, @jukent!

2022-05-06 00:11 UTC, mgrover1 approved these changes
Fantastic work @jukent !!

2022-05-06 17:00 UTC, merged