BinderHub maintenance 12/19/2024 post
ProjectPythia/projectpythia.github.io pull request #479
Opened 2024-12-18 21:47 UTC by ktyle

2024-12-18 22:15 UTC, jukent requested changes
The admonition isn't rendering properly
<img width="984" alt="Screenshot 2024-12-18 at 3 12 27 PM" src="https://github.com/user-attachments/assets/a4c864cd-f68b-4183-9b2e-dc177c4bd6b0" />

2024-12-18 22:15 UTC, jukent commented on portal/index.md
> +<a href="posts/binderhub_status.html" role="button" class="btn btn-light btn-lg" style="display: flex; align-items: center; font-weight: 600; text-decoration: none; background-color: "orange"; border
```suggestion
<a href="posts/binderhub_status.html" role="button" class="btn btn-light btn-lg" style="display: flex; align-items: center; font-weight: 600; text-decoration: none; background-color: orange; border: rgba(var(--spt-color-dark), 1);">
```

2024-12-19 20:26 UTC, brian-rose approved these changes
LGTM!

2024-12-19 20:30 UTC, jukent approved these changes

2024-12-19 20:51 UTC, merged