Gallery
ProjectPythia/projectpythia.github.io pull request #51
Opened 2021-02-17 19:20 UTC by jukent

Some work to create a separate links gallery. See #44.

This PR currently does not pass the tests. I have made some progress but am stuck at the error 
```
Extension error:
Handler <function main at 0x111735700> for event 'builder-inited' threw an exception (exception: name 'dedent' is not defined)
make: *** [html] Error 2
```
and am having a hard time tracking it down. I see where `dedent` is called, but cannot see the difference between its call in `yaml_gallery_generator.py` and in `conf.py`. I am also wondering if the numbers in the error are significant.

2021-02-17 19:24 UTC, andersy005 commented
@jukent, you are missing an import:

```python
from textwrap import dedent
```

2021-02-17 19:36 UTC, jukent commented
> @jukent, you are missing an import:
> 
> ```python
> from textwrap import dedent
> ```

Thank you so much!

2021-02-17 19:50 UTC, andersy005 commented
> Thank you so much!

Of course!

2021-02-17 19:53 UTC, jukent commented
To Do:

Make tags clickable / searchable
Make description collapsed with option to expand it
Add images for each links.yaml entry
Use more author information

2021-04-12 15:08 UTC, jukent commented
@ProjectPythia/education Please take a look at this and let me know if you'd like any descriptions, author information, or categories changed for a given entry. Any other comments are appreciated.

2021-04-14 17:37 UTC, clyne commented
> @ProjectPythia/education Please take a look at this and let me know if you'd like any descriptions, author information, or categories changed for a given entry. Any other comments are appreciated.

What is the best way to view this information? I don't seem to be able to build locally following our contributor's guide and not sure where to look if I'm successful :-)

2021-04-14 18:31 UTC, jukent commented
@clyne I can build it locally with 
```
make html
open _build/html/index.html
```

Is that not working for you? Alternatively you can click "Show all checks" next to the green "All checks have passed". Then select "Details" and you will see a test build of the site.

2021-04-14 21:08 UTC, clyne commented
> @clyne I can build it locally with
> 
> ```
> make html
> open _build/html/index.html
> ```
> 
> Is that not working for you? Alternatively you can click "Show all checks" next to the green "All checks have passed". Then select "Details" and you will see a test build of the site.

My bad. I wasn't in the content directory. Thanks.

2021-04-14 21:18 UTC, clyne commented
> @ProjectPythia/education Please take a look at this and let me know if you'd like any descriptions, author information, or categories changed for a given entry. Any other comments are appreciated.

I think it would be helpful to try to come up with an initial set of classifiers to choose from for each of the entries. In the future external contributors could be provided a list to choose from as appropriate. Here is a first stab at sets and elements to consider:

Packages: numpy, matplotlib, xarray, dask, metpy, geocat, etc.
Formats: video, gallery, book, course
Level: beginner, intermediate, advanced
Science topics: climate, weather, ocean, etc.
Technologies: Python, Conda, GitHub, etc.

Thoughts?

2021-04-22 22:38 UTC, jukent commented
At last week's meeting we decided we'd merge this as everyone who spoke up felt it was an improvement over the current table. For some reason I am struggling to request review from @ProjectPythia/infrastructure

2021-04-23 15:51 UTC, brian-rose commented
This is all new to me, but GitHub offered me a button called "ready for review". Clicking it seems to have triggered the review requests based on who's listed as CODEOWNERS.

I'm not sure if we have the teams enabled for this repo? @andersy005 do we need to take some action to active that?

2021-04-23 16:03 UTC, brian-rose requested changes
I just sharpened the description of my Climate Laboratory book.

Everything else looks fine to me at first glance. I hope we can merge this and tweak details in future PRs, especially as we get more eyes on these pages. E.g. the authors of some of the external resource might be interested in contributing an updated description.

2021-04-23 16:12 UTC, dopplershift commented
@brian-rose For future reference, clicking "ready for review" converts the PR from a "Draft" to one that's can be merged/considered ready for review.

2021-04-23 18:37 UTC, jukent commented on content/links.yaml
> +    A hands on approach to climate physics and climate modeling. This JupyterBook serves as a course textbook at the University of Albany. It is self-reproducing, free and open, interactive, and is a
Made this change in the most recent push.

2021-04-23 18:39 UTC, brian-rose approved these changes

2021-04-28 16:40 UTC, mgrover1 approved these changes
This looks great!!

2021-04-28 17:11 UTC, merged